### ISSUE TITLE
nestjs+sequelize

### ISSUE THREAD

**Issue by Mitch-i** [RobinBuschmann/sequelize-typescript#1141]
If I try like:

async create(createUserDto: CreateUserDto): Promise<User> {
  return await this.userModel.build(createUserDto)
}
Get error:

Argument of type 'CreateUserDto' is not assignable to parameter of type 'User'.
Type 'CreateUserDto' is missing the following properties from type 'User': creationDate, deletionDate, updatedOn, users, and 43 more.

Why it doesn't work like in this example?

**Comment by uandi4446** [comment]
Hello, Mitch.

I believe the build method needs user model instance include the metadata.
The definition of the build method in sequelize document,
**"Build a new model instance."**

I think you would use await this.userModel.create method if you want to use the createUserDto. It will make a new model instance with the dto, and than build it.

If you want to build method like the example, you would pass the user model instance instead of the dto instance.

**Comment by Mitch-i** [comment]
it was because in examples is define model like that
Class x extend Model<X> {} 
but not
Class x extend Model<CreateDto, UpdateDto> {}
