### ISSUE TITLE
Move @types/sequelize constraint to >= ?

### ISSUE THREAD

**Issue by bilby91** [RobinBuschmann/sequelize-typescript#142]
Hey @RobinBuschmann,

Are you okey if we change the @types/sequelize constraint to `>=` ? We are not able to use the latest types that include some definitions that we need.

Thanks!

**Comment by RobinBuschmann** [comment]
Hey @bilby91 , I thought about it too. But the problem is, in case of typings that are not compatible with sequelize-typescript, we wouldn't notice the issue fast enough. So that all beginners new to sequelize-typescript couldn't use sequelize-typescript until the typings are fixed. 
Let us publish patch releases with the latest typings more frequently instead. So that we have full control over it :) what do you think?

**Comment by bilby91** [comment]
Hi @RobinBuschmann ! Sure, that should work. I was thinking of another option maybe. Having a CI run with the latest version always. I guess the problem with that will be that if we don't commit frequently to the repo we won't notice the incompatibility. Let's go with your idea!

**Comment by bilby91** [comment]
@RobinBuschmann #143 😃
