### ISSUE TITLE
Drop sequelize version 3 support for future releases

### ISSUE THREAD

**Issue by RobinBuschmann** [RobinBuschmann/sequelize-typescript#157]
Supporting v3 and v4 at the same time makes the code base unnecessarily complex and improvements much more difficult. Since sequelize v4 is available for some month now, I think it makes sense to drop support for version 3.

@bilby91 @snewell92 @BruceHem What do you think about it?

**Comment by bilby91** [comment]
I have the same opinion here! 

+1

Martín

On Sat, Oct 07, 2017 at 12:01 Robin Buschmann

<
mailto:Robin Buschmann <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Supporting v3 and v4 at the same time makes the code base unnecessarily complex and improvements much more difficult. Since sequelize v4 is available for some month now, I think it makes sense to drop support for version 3.

https://github.com/bilby91 https://github.com/snewell92 https://github.com/brucehem
What do you think about it?

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/RobinBuschmann/sequelize-typescript/issues/157
, or

**Comment by BruceHem** [comment]
@RobinBuschmann to be honest, I think it's best to drop support for v3.

**Comment by nullpixel** [comment]
+1

**Comment by snewell92** [comment]
I agree.

And if someone needs v3 support (lock in on production or something), it would be easy to either 1, pin `sequelize-typescript` to an older version with v3 support, or 2 - fork this repo, reset to a commit with v3 support, and just use that indefinitely (since sequelize v3 isn't going to undergo any major breaking changes, barring some security issue... in which case the sequelize team may still just advise to update to v4).

Let's do eeeeet!

**Comment by RobinBuschmann** [comment]
Sequelize version 3 support will be dropped with `sequelize-typescript@1.0.0`. `sequelize-typescript@0.6.0` will be the last minor release before `1.0.0`.

**Comment by RobinBuschmann** [comment]
Dropped on `sequelize-typescript@1.0.0-alpha-X`
