### ISSUE TITLE
Roadmap & Contributing

### ISSUE THREAD

**Issue by mzgnr** [RobinBuschmann/sequelize-typescript#2]
hey, nice work! Do you have any roadmap that you can share ? I would like to contribute to make it more stable. I've also seen that you are working on refactoring branch.

**Comment by RobinBuschmann** [comment]
Hey, thanks. Hopefully I can publish a first version in the next two weeks. What's left to do:

- make it also compatible with the next version of sequelize, so that it will work with sequelize v3 and v4.
- find a way to make the `add<Relational-Model>`,  `set<Relational-Model>` syntax type safe.
- adopt some more tests of the original sequelize repo
- documentation (readme mostly)
- (more validation annotations)
- (make validation only possible (so that it will work with any db connection))

The refactoring branch will replace the whole master branch. An awkward limitation will be fixed, so that the created instances will return `true` on `instanceOf` check, like `person instanceOf Person === true`.

(I hope this helps)

But yeah, you can contribute to this repo, if you like to :)

**Comment by RobinBuschmann** [comment]
@mzgnr are you still interested in contributing? If so, feel free to do so. I would appreciate it.

Or do you have further remarks, ideas or basic requirements that I have overseen?

**Comment by snewell92** [comment]
@RobinBuschmann I ran across this project and it is just what I needed. Was trying to get Sequelize v4.0 working in a project, but with more tooling support. Then BAM. Robin Bushmann to the rescue.

Thanks 👍 

As @mzgnr brought up though, having a roadmap, contributing guide, open issues, etc. would help in directing possible collaborators. I'll be glad to open any issues I come across (none so far 😸) and, hopefully, take a stab at learning and helping with development.

**Comment by RobinBuschmann** [comment]
@snewell92 thank you for your helpful input. You're right, a roadmap and a contributing guide would be very useful. Do you know of a good template for a contributing guide? thanks :) 

Regarding any roadmap, there are currently no new features planned except of #10. But if there are any improvements on your mind... I appreciate any help.

**Comment by snewell92** [comment]
I just ran into a problem with the sequelize types (not having `alter: true` option in `SyncOptions` so I might open a PR to just update the types of sequelize. I suppose I'll keep using it and open PR's when necessary, as it is I'm just now learning sequelize.

As far as a contributing guide - a few googles and clicks and I came up with the following.

- [Overkill atom guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md)
- [A template](https://github.com/nayafia/contributing-template)
- Probably good to reference the [Typescript guide](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request) (has links to the handbook)
- This one seems really good. A lot bigger, but similar. [InversifyJS contributing guide](https://github.com/inversify/InversifyJS/blob/d552f0370fcb48f1c8f3bbe48e8c70abafc5221a/CONTRIBUTING.md)

I will say, your README documentation is **stellar** 🌟. Really, great job.
