### ISSUE TITLE
[Question] Examples of migrating a codebase from classic Sequelize to sequelize-typescript?

### ISSUE THREAD

**Issue by microsoftly** [RobinBuschmann/sequelize-typescript#438]
Are there any good examples of how to iteratively move a codebase to use `sequelize-typescript`? I'd like to use the module, but it seems too risky to do a massive refactor

**Comment by RobinBuschmann** [comment]
Hey @microsoftly, if an additional database connection isn't an issue for you, you could only migrate a few models to sequelize-typescript and run both - st and classic sequelize - in parallel.

The only difference between sequelize-typscript and sequelize is that st uses a different default configuration for the model define options:
```ts
{
  timestamps: false,
  freezeTableName: true
}
```
But those ones can be easily overridden like `new Sequelize({define: {/* here */}})`. If you have any further questions don't hesitate to ask them :)

**Comment by microsoftly** [comment]
Do you have any examples for reference? It looks like using st as a drop in replacement for sequelize will work, but I'm having trouble getting around associations where some are classic and some are st ified

**Comment by Vi-jay** [comment]
migrate is very easy 
just change `sequelize` to st
and add your sequelize-typescript ` model` to instance

import Car from '../models/Car';
const db = new Sequelize({
   ...
});
// This is a model of the sequelize-typescript type added later.
// You don't need to modify the previous model.
db.addModels([Car]);

**Comment by RobinBuschmann** [comment]
@microsoftly sry for the late reply: You either need to migrate the associated models as well or you could keep the corresponding classic model definition together with the new one until you‘ve also migrated the associated one. But unfortunately you cannot use an st model together with a sequelize model if their are referenced in different instances.
Hope this helps

**Comment by RobinBuschmann** [comment]
Close this issue due to inactivity

**Comment by MagicLegend** [comment]
Sorry for ripping open this old question again, but I'm facing the same right now, and I don't know how to solve this based on the existing comments. I have an existing codebase written in plain JS, and I'm working on switching to TS. Given the complexity and time constraints I really cannot spend time on refactoring all the existing models **and their calls** to TS.

> @microsoftly sry for the late reply: You either need to migrate the associated models as well or **you could keep the corresponding classic model definition together with the new one until you‘ve also migrated the associated one**. But unfortunately you cannot use an st model together with a sequelize model if their are referenced in different instances.
> Hope this helps

*(Emphasis added)*

@RobinBuschmann your comments to this issue sound like it is possible to use both the original `.js` model and the new `.ts` models side-by-side. How would this work?

It can be assumed that the new models only interact with the existing ones on two occasions for now; one many-to-many (Table `I` to table `T`) and one one-to-many (Table `P` to table `A`, oldjs-to-newts respectively). The other existing relationships can be dealt with the 'old' way for now.

So far I've made some attempts at convincing `sequelize-typescript` to use the old `.js` models, but with no success. Is this because the old `.js` models should be handled through `sequelize` itself, and the new `.ts` models through st? How would this go about in the startup phase, since the two instances need to reference the same tables on table `I` and `P`?
