### ISSUE TITLE
Cannot define a varbinary column type.

### ISSUE THREAD

**Issue by pburrows** [RobinBuschmann/sequelize-typescript#5]
Sequelize does not natively support the binary column types, but their recommendation is to use the string 'binary(100)' or 'varbinary(max)' etc... when specifying the column type.

I've tried many variations of this, and don't seem to be able to specify the column correctly for my password field. I've tried this:

	@Column({type: "VARBINARY(MAX)")
	Password: any;

and

	@Column({type: "VARBINARY(MAX)")
	Password: string;

and

	@Column(DataType.STRING)
	Password: string;

(which I don't expect to work, of course)
and

	@Column("VARBINARY(MAX)")
	Password: string;

and probably a couple others.

Every single time, I get an error:

    SequelizeDatabaseError: Implicit conversion from data type nvarchar to varbinary is not allowed. Use the CONVERT function to run this query.

when it tries to run a query like this:

    UPDATE [User] SET [Password]=N'$2a$11$ynNqEXn1xf7y.0/cXVN.CugvvBQ2uaARqbXV8Ck59EYAigB027D6G' OUTPUT INSERTED.* WHERE [UserId] = 1000

**Comment by RobinBuschmann** [comment]
@pburrows You're using mssql, right? Could you try it with `DataType.BLOB`. Sequelize will internally map this to `VARBINARY(MAX)` and will do some validation and conversion for you. Probably this helps. I have not much experience with mssql and currently no mssql server running, which I can test on.
If this doesn't work, you could ask the sequelize team or on stackoverflow for help. Since this doesn't seem to be an sequelize-typescript issue.

**Comment by pburrows** [comment]
`DataType.BLOB` worked! Thanks for your help. Wish I'd thought of that.
