### ISSUE TITLE
Readme clarification request: difference between using this and directly using sequelize v5

### ISSUE THREAD

**Issue by papb** [RobinBuschmann/sequelize-typescript#588]
I am new to TS, so this might be trivial, so sorry about that in advance. But, asking directly: now that Sequelize v5 ships TS typings, what advantages does this library still add? I think it would be nice to have this clarified in the readme, so that one can immediately know it without further digging. (Unless there is a super obvious answer, in which case I am respectfully sorry, I am very new to TS).

Thanks for looking :)

**Comment by BadCoder1337** [comment]
This lib provides a lot of magnificent features like clear model definition with methods, quick hints for data fields, decorators and etc

**Comment by RobinBuschmann** [comment]
Hey @papb thanks for your question :) the main goal of sequelize-typescript is not to provide typings - this was already solved with `@types/sequelize`. As BadCoder1337 stated, sequelize-typescript provides decorators and some other features in order to simplify model definition, create relations between models and more. For example, see model definition with pure sequelize: http://docs.sequelizejs.com/manual/models-definition.html and with sequelize-typescript on the other hand https://github.com/RobinBuschmann/sequelize-typescript/blob/master/README.md#model-definition. With the latter one you‘ll have your type and your table setup at one place.

**Comment by papb** [comment]
I see!! Thanks @BadCoder1337 and @RobinBuschmann  :grin:
