### ISSUE TITLE
Can be used with Ionic2?

### ISSUE THREAD

**Issue by olaferlandsen** [RobinBuschmann/sequelize-typescript#62]
My Question is about if I can be used it with Ionic2 on Android or iOS or both?
Thanks

**Comment by RobinBuschmann** [comment]
Actually, sequelize is supposed to be used on server side only. But probably there is a way to make it work with sqlite on android and ios. I did not tried it yet. If you have time to investigate this, you could share your learnings here if you like to :)

**Comment by snewell92** [comment]
@olaferlandsen 

You should test it, [but this guy thinks so](https://www.techiediaries.com/mobiledev/ionic2-sqlstorage-with-sqlite-and-cordova/). Including Sequelize, and sequelize-typescript shouldn't be a problem (I don't think it does any crazy native bindings or anything... but again - I'd test it out on the *Ionic View* app)

**Comment by olaferlandsen** [comment]
sequelize-typescript does not work with cordova/phonegap, therefore it does not work with ionic.

**Comment by RobinBuschmann** [comment]
Hey @olaferlandsen, thanks for investigating this. Can you share problems you faced while trying to make it work with sequelize-typescript?

**Comment by snewell92** [comment]
The referenced blog only shows how to add a cordova plugin to get SQLite working without sequelize. It is probable that sequelize would need a specific dialect/adapter for cordova/phonegap that uses that plugin, or at least someway to tell sequelize - hey, I'm using SQLite, and I need to use `SQLite` from `ionic-native` instead of the normal SQLite dialect/adapter.
