### ISSUE TITLE
getters/setters type issue

### ISSUE THREAD

**Issue by spearmootz** [RobinBuschmann/sequelize-typescript#676]
**Versions**

- sequelize: 5.18.4
- sequelize-typescript: 1.0.0
- typescript: 3.6.2

**I'm submitting a ...** 

[ x] bug report
[ ] feature request

**Actual behavior:**

Getters this.getDataValue returns the type declared on the class property and not on the Column.type.

**Expected behavior:**

this.getDataValue returns a type value stipulated by the Column.type if stipulated

**Steps to reproduce:**

Just declare any Model class.

**Related code:**

```ts
class Account extends Model<Account> {
@AllowNull
  @Column({
    type: DataType.DATEONLY, // SHOULD BE WHATEVER THIS IS
    get(this: Account): moment.Moment | null {
      const date = this.getDataValue('date_discharged'); // TYPESCRIPT SAYS THIS IS MOMENT | UNDEFINED
      return getDate(date);
    },
    set(this: Account, val: moment.Moment | null) {
      this.setDataValue('date_discharged', val == null ? null : val.format());
    }
  })
  date_discharged?: moment.Moment; // BECAUSE OF THIS, I DO THIS TO USE MOMENT INSTEAD OF DATES.
}

```

**Comment by RobinBuschmann** [comment]
Hey @spearmootz thanks for reporting. Unfortunately this cannot be fixed within sequelize-typescript, but need to be solved on sequelize side. The actual issue is the type of `getDataValue`: https://github.com/sequelize/sequelize/blob/master/types/lib/model.d.ts#L2551. As your example makes it very clear, the internal type (the type stored in dataValues) doesn't necessarily need to be the type of the property type. Can you open an issue in the sequelize repo, please?

**Comment by spearmootz** [comment]
i have opened an issue here.  i tried to fix it but failed to do so, in the issue i have my observations which for a typescript master its probably rubbish.

https://github.com/sequelize/sequelize/issues/11558
