### ISSUE TITLE
"Error: Model not initialized: Member "findOne" cannot be called. "u" needs to be added to a Sequelize instance"

### ISSUE THREAD

**Issue by webhacking** [RobinBuschmann/sequelize-typescript#678]
**Versions**

- sequelize: 
- sequelize-typescript: 
- typescript

**I'm submitting a ...** 

[ ] bug report
[ ] feature request

```
Model not initialized: Member "findOne" cannot be called. "u" needs to be added to a Sequelize instance
```

**Comment by RobinBuschmann** [comment]
Hey @webhacking, can you provide an example repo which reproduces the issue?

**Comment by KokomiShiina** [comment]
> Hey @webhacking, can you provide an example repo which reproduces the issue?

Hi, I am having the same issue. Looks like a chicken and egg problem.

My code looks like this.

```ts
export const sequelize = new Sequelize(
    {
        // ...
        models: [__dirname + "/Models/**/*.model.ts"]
    }
);
```

Where I look at the runtime param, `__dirname` is pointing to the folder where the TypeScript files are compiled into JavaScript. So it cannot resolve `*.model.ts` inside the `lib` folder. Where my `src` folder have all the models in TypeScript.

I've tried replacing the `.ts` with `.js`. It seems to find the file. But another warning 

> No default export defined for file "u.model" or export does not satisfy filename

I guess that's because JavaScript files do not have export.

Is there anyway I can work around this?

**Comment by KokomiShiina** [comment]
> Hey @webhacking, can you provide an example repo which reproduces the issue?
> 
> Hi, I am having the same issue. Looks like a chicken and egg problem.
> My code looks like this.
> export const sequelize = new Sequelize(
>     {
>         // ...
>         models: [__dirname + "/Models/**/*.model.ts"]
>     }
> );
> Where I look at the runtime param, __dirname is pointing to the folder where the TypeScript files are compiled into JavaScript. So it cannot resolve *.model.ts inside the lib folder. Where my src folder have all the models in TypeScript.
> I've tried replacing the .ts with .js. It seems to find the file. But another warning
> 
> No default export defined for file "u.model" or export does not satisfy filename
> 
> I guess that's because JavaScript files do not have export.
> Is there anyway I can work around this?

My bad, just figured out I need to use the `modelMatch` function for `.model` suffix. It gets to work finally.

However, the document point us to use globs in `.ts` which cannot be resolved. I ended up using `.js` or the Model will not be initialized.

I guess a framework might have been used during the development (?). But `.js` has to be used in pure TypeScript.
