### ISSUE TITLE
Auto generated foreign key does not exist

### ISSUE THREAD

**Issue by SamiSammour** [RobinBuschmann/sequelize-typescript#758]
**Versions**

- sequelize: 5.21.5
- sequelize-typescript: 1.1.0
- typescript: 3.8.3

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Actual behavior:**

When creating a belongs to association typescript cannot resolve the auto generated foreign key
**Expected behavior:**

I can set/get the auto generated foreign key
**Steps to reproduce:**

```
@Table
class Player extends Model<Player> {

  @Column
  name: string;

  @Column
  num: number;

  @BelongsTo(() => Team, 'teamId')
  team: Team;
}

@Table
class Team extends Model<Team> {

  @Column
  name: string;

  @HasMany(() => Player)
  players: Player[];
}
```
I cannot state `player.teamId` without adding the column manually inside the `Player` model like this:
```
  @ForeignKey(() => Team)
  @Column
  teamId: number;
```

It would be very useful if I can access `player.teamId` without having to add it manually for every association

**Comment by RobinBuschmann** [comment]
Hey @SamiSammour thanks for bringing this up. Unfortunately this won't work. There is no way to define it so that typescript can infer the property key you've defined in a decorator. You have to explicitly define it in your model: 

```ts
  teamId: number;
```

But what we probably could do is improving the types of the decorators. So that only keys of the model can be used as foreign key. For example, if you use a key `someKey` which is not part of the model, the compiler would throw an error.

Hope this helps!

**Comment by SamiSammour** [comment]
> But what we probably could do is improving the types of the decorators. So that only keys of the model can be used as foreign key. For example, if you use a key `someKey` which is not part of the model, the compiler would throw an error.

That would be helpful in deed
