### ISSUE TITLE
usage in multi sql schema

### ISSUE THREAD

**Issue by lessu** [RobinBuschmann/sequelize-typescript#77]
In my case , there's one User Model in 2 different mysql server or schema.(A and B)
how to use  A.User.or B.User explicitly?

**Comment by RobinBuschmann** [comment]
The model definitions for A.User and B.User are the same? If so, sequelize-typescript is not supposed to work with one class for multiple different connections. This is because sequelize uses static functions for the typical ORM-methods like `find()`, `findAll` and so on. 

But you could achieve it anyway with a base class:
folder structure:
```
models/
   base/
      BaseUser.ts
   connection-a/
      User.ts
   connection-b/
      User.ts
```

```typescript
class BaseUser<T> extends Model<T> {
  @Column
  email: string;
}
```
```typescript
// connection-a/
@Table
class User extends BaseUser<User> {}

new Sequelize({modelPaths: [__dirname + '/models/connection-a']});
```
and same for:
```typescript
// connection-b/
@Table
class User extends BaseUser<User> {}

new Sequelize({modelPaths: [__dirname + '/models/connection-b']});
```

**Comment by lessu** [comment]
Thank you very much.
