### ISSUE TITLE
npm dependencies

### ISSUE THREAD

**Issue by Pritilender** [RobinBuschmann/sequelize-typescript#8]
Hi, I've noticed that dependencies in `package.json` are a bit mixed up: `@types` are in `dependencies` and regular libraries that are used are in `dev-dependencies`.

The thing is that npm won't install `dev-dependencies` when you install the package, but only `dependencies`. So if you say that someone needs to install `reflect-metadata` when they install this package, that's an obvious "smell" you need it in your `dependencies`.

I'll make a PR soon with a fix 🙂

**Comment by RobinBuschmann** [comment]
Hey thanks for your advice :) But there is a reason why these dependencies are listed in the corresponding dependency configuration (`dependecies`/`devDependencies`).

`reflect-metadata` should not be installed by default when using `sequelize-typescript`.This is to ensure, that never multiple `reflect-metadata` packages exist in one project. This is because of how `reflect-metadata` stores the information. For example if there is a version conflict between two `reflect-metadata` dependencies, you will end up with two `reflect-metadata` packages. In this case I faced the issue, that arbitrary meta data is stored in one `reflect-metadata` package and later tried to retrieve from the other, in which of course, the meta data couldn't be found. I agree, that there could be a better way of handling these dependencies: `peerDependencies` could be a way to go. But I didn't get these to work as I expected (NPM complains about missing peer dependencies despite of there are installed). So I decided not to using `peerDependencies`. But If you can help me on this I would appreciate it :) The reason why `reflect-metadata` exists in `devDependencies`: It is needed for testing.

`@types/*` dependencies: These dependencies are listed in `dependencies` because `sequelize-typescript` provides typings by default. So when using `sequelize-typescript` with typescript you will need the `@types/*` dependencies as well. Or did I overseen something?

**Comment by RobinBuschmann** [comment]
@Pritilender As you also mentioned sequelize in your pull request: The consumer of `sequelize-typescript` should be able to choose which sequelize version they want to use. So that also sequelize is a peer dependency :)

**Comment by Pritilender** [comment]
@RobinBuschmann Oh, I see. I wasn't thinking about having different versions. 

For `@types`, I think that all type packages are dev dependencies, but if you want to ensure that the user has out of the box support for sequelize in TS, then it makes sense to have it there.

As far as help is concerned, I'm glad to help you. This would be my first open-source contribution, so I'd appreciate if you would give me some advice, or write some contributor guide. I can take a look at this thing with `peerDependencies` first. I'm currently working on a project that uses this package, so I'll be writing down some issues I find. Also, if you have some kind of a roadmap for v1.0, that would be nice to be somewhere publicly available.

**Comment by RobinBuschmann** [comment]
@Pritilender Good to here that you will include `sequelize-typescript` in your project :) 

Regarding contribution: I don't have any guidelines yet. For every newly added feature, tests should be implemented. When writing an issue, questions, advices,..  any help is greatly appreciated.

Since all `sequelize` features are available with `sequelize-typescript` (or did I missed one?), there are no features on my list for an update to v1.0. But before I will update this repo to a major version, I would like to use it a little bit more on my own projects, to ensure that it is ready for production. But if you have any features in you mind, feel free to contribute them :)

Anyway I do have some ideas for new features. I will create an issue with a proposal soon. If you like to discuss about it.

If it is ok for you, I will close this issue(?) (Feel free to post any further questions in this issue)

**Comment by Pritilender** [comment]
@RobinBuschmann It's cool :)
